dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    # 192.168.40.128:2181,192.168.40.128:2182,192.168.40.128:2183
#    address: zookeeper://192.168.40.128:2181
    address: nacos://127.0.0.1:8848
    protocol: nacos
  consumer:
    check: false
spring:
  monitor:
    protocol: registry
  application:
    name: dubbo-springboot-demo-consumer